#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""syndatagenerators documentation build configuration file.

created by ``sphinx-quickstart`` on Fri Feb  9 13:32:39 2018 and heavily modified.

This file is execfile()d with the current directory set to its containing dir.

Note that not all possible configuration values are present in this autogenerated file.

All configuration values have a default; values that are commented out serve to show the default.

If extensions (or modules to document with autodoc) are in another directory,
add these directories to sys.path here. If the directory is relative to the documentation root,
use os.path.abspath to make it absolute, like shown here.

>>> import os
>>> import sys
>>> sys.path.insert(0, os.path.abspath('.'))
"""
import os
import sys
import importlib


IMPORT_NAME = 'syndatagenerators'  # name used for imports

# Add the path of our module to the import searchpath (uncomment to use)
# import sys
# sys.path.insert(0, os.path.abspath('..'))

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Example configuration for intersphinx: refer to the Python standard library.
# TODO: link all the other mentioned packages, like .database etc. here.
intersphinx_mapping = {'https://docs.python.org/': None}


# ======================================================================================
# No configurable options below this line


# Get current version etc. from the `__about__.py` file --------------------------------
# Very evil way to retrieve the variables contained in about.
# Those will be added to the current scope
PROJECT_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(PROJECT_PATH)
about = importlib.import_module(IMPORT_NAME + '.__about__')

# -- General configuration -------------------------------------------------------------
# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',  # generate docs from docstrings
    'sphinx.ext.napoleon',  # does some formatting tricks
    'sphinx_autodoc_typehints',  # package needs to be installed
    # 'sphinx.ext.doctest',  # if you want to use doctests somehow
    'sphinx.ext.imgmath',  # render latex graphics
    'sphinx.ext.intersphinx',  # links to other () packages
    'sphinx.ext.coverage',  # documentation coverage (not test coverage)
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = about.__title__
copyright = about.__copyright__
author = ', '.join(about.__authors__)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# Get current version from the version file
# The full version, including alpha/beta/rc tags.
release = about.__version__  # (we don't use any such tags)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False
autodoc_warningiserror = False  # Some warnings can happen

# -- Options for Napoleon extension ---------------------------------------
# Allow Google style docstrings, but disallow Numpy style docstrings.
# For the sake of consistency it is a good idea not to mix those.
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    # 'footerbgcolor': '#1f82c0',  # Fraunhofer blue
    # 'sidebarbgcolor': '#1f82c0',
    # 'relbarbgcolor': '#1f82c0',
    # 'headbgcolor': '#1f82c0',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_favicon = '_static/favicon.png'
html_logo = 'logo.png'  # automatically in `_static`

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
        # 'donate.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------
# Output file base name for HTML help builder.
htmlhelp_basename = 'pydoc'


# -- Options for LaTeX output ---------------------------------------------
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [(
    master_doc,
    IMPORT_NAME + '.tex',
    about.__title__ + ' Documentation',
    ', '.join(about.__authors__), 'manual'
)]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(
    master_doc,
    IMPORT_NAME,
    about.__title__ + ' Documentation',
    about.__authors__, 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, about.__title__, about.__title__ + ' Documentation',
     about.__author__, about.__title__, about.__description__,
     'Miscellaneous'),
]
